include:
  - project: 'sfdx/sfdx-cicd-template'
    file: 'Salesforce.gitlab-ci.yml'
    ref: stable

# This yml file calls a pre-configured file for Salesforce DX projects that is located in https://gitlab.com/sfdx/sfdx-cicd-template.
# To learn more about what the yml file does and how to configure your repository to work with this template, review the README in the template repository.
